// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: password_resets.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPasswordReset = `-- name: CreatePasswordReset :one

INSERT INTO password_resets (user_id, token_hash, expires_at)
VALUES (
    $1,
    $2::bytea,
    $3::timestamptz
)
RETURNING id, user_id, created_at, expires_at, used_at
`

type CreatePasswordResetParams struct {
	UserID    string
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
}

type CreatePasswordResetRow struct {
	ID        string
	UserID    string
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
}

// Password resets. Like sessions and invitations, the token itself never
// reaches this file: what is stored and what is looked up is its SHA-256,
// computed in the domain layer (ADR-0005). And like both of them, token_hash is
// never selected -- nothing outside confirmation may see it, and one stray
// column in a row is a credential on its way into a JSON body.
//
// There is no address anywhere here. The row points at an account by id, so a
// link requested before somebody changed their address cannot resurrect the old
// one.
func (q *Queries) CreatePasswordReset(ctx context.Context, arg CreatePasswordResetParams) (CreatePasswordResetRow, error) {
	row := q.db.QueryRow(ctx, createPasswordReset, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i CreatePasswordResetRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const expireOpenPasswordResetsForUser = `-- name: ExpireOpenPasswordResetsForUser :execrows
UPDATE password_resets
SET expires_at = now()
WHERE user_id = $1
  AND used_at IS NULL
  AND expires_at > now()
`

// Asking for a second link. The previous one stops working the moment a new one
// is sent, rather than every link ever requested staying live until its own
// deadline -- somebody who clicks "forgot password" four times should not leave
// four ways into their account lying in an inbox.
//
// Spent rows are left alone: they are the record that a password was replaced
// through them, and rewriting their deadline would rewrite that history.
func (q *Queries) ExpireOpenPasswordResetsForUser(ctx context.Context, userID string) (int64, error) {
	result, err := q.db.Exec(ctx, expireOpenPasswordResetsForUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPasswordResetByTokenHash = `-- name: GetPasswordResetByTokenHash :one
SELECT id, user_id, created_at, expires_at, used_at
FROM password_resets
WHERE token_hash = $1::bytea
`

type GetPasswordResetByTokenHashRow struct {
	ID        string
	UserID    string
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
}

// Confirmation. Expiry and use are deliberately not filtered here, for the same
// reason GetInvitationByTokenHash does not filter them: the caller has to tell a
// spent link from one that never existed for the log, and a WHERE clause that
// hides the row makes the two indistinguishable. What the caller must not do is
// let that difference reach the client -- see PasswordReset.IsUsable.
func (q *Queries) GetPasswordResetByTokenHash(ctx context.Context, tokenHash []byte) (GetPasswordResetByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getPasswordResetByTokenHash, tokenHash)
	var i GetPasswordResetByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const usePasswordReset = `-- name: UsePasswordReset :execrows
UPDATE password_resets
SET used_at = now()
WHERE id = $1::uuid
  AND used_at IS NULL
  AND expires_at > now()
`

// Stamping the reset as spent, and the only thing that makes it single-use.
//
// The conditions are in the WHERE rather than checked in Go beforehand. Two
// confirmations of the same link arriving together would both read an open row
// and both go on to write a password; here the second one updates no rows and
// the caller can see that it lost. The password is written in the same
// transaction as this statement, so a confirmation that loses changes nothing --
// which matters more than it does for invitations, because the loser would
// otherwise set the password of an account that is already somebody's.
func (q *Queries) UsePasswordReset(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, usePasswordReset, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
