// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	// Login. Compared with lower() because addresses are not case sensitive and
	// users_email_key indexes lower(email) for exactly this lookup.
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	// Every read goes through users_live, never through users. The view is where
	// soft delete is enforced (docs/data-model.md); a query that names the table
	// directly is one forgotten WHERE away from returning deleted accounts.
	//
	// The two exceptions are the writes below, which have to name the table
	// because a view is not what you insert into or soft-delete through.
	GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error)
	ListUsers(ctx context.Context) ([]ListUsersRow, error)
	// Masking, not deleting: the account keeps its rows so that its cards and
	// comments survive with an author (docs/data-model.md, retention). The address
	// is replaced rather than blanked so the partial unique index frees the
	// original for reuse.
	SoftDeleteUser(ctx context.Context, id string) (int64, error)
}

var _ Querier = (*Queries)(nil)
