// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"
)

type Querier interface {
	// Stamping the invitation as used, and the only thing that makes it single-use.
	//
	// The conditions are in the WHERE rather than checked in Go beforehand. Two
	// clicks on the same link arriving together would both read an open invitation
	// and both go on to create an account; here the second one updates no rows and
	// the caller can see that it lost. The account is created in the same
	// transaction as this statement, so a redemption that loses creates nothing.
	AcceptInvitation(ctx context.Context, id string) (int64, error)
	// Invitations. Like sessions, the token itself never reaches this file: what is
	// stored and what is looked up is its SHA-256, computed in the domain layer
	// (ADR-0005). And like sessions, token_hash is never selected — nothing outside
	// redemption may see it, and one stray column in a list is a credential sitting
	// in a JSON body.
	//
	// invitations.role holds the ACCOUNT role the invitee will be created with
	// (ADR-0012). The CHECK on the column accepts only maintainer, contributor, and
	// viewer: there is exactly one owner and that account is the first one, not an
	// invited one.
	CreateInvitation(ctx context.Context, arg CreateInvitationParams) (CreateInvitationRow, error)
	// Sessions. The token itself never reaches this file: what is stored and what
	// is looked up is its SHA-256, computed in the domain layer (ADR-0005).
	CreateSession(ctx context.Context, arg CreateSessionParams) (CreateSessionRow, error)
	// The account role is chosen by whoever creates the account, never defaulted
	// here: users.role has a DEFAULT, and relying on it would mean a caller that
	// forgets to decide silently gets one (ADR-0012).
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	// Signing out everywhere else. The session making the request is kept, because
	// the caller asked to end the others and an answer they cannot receive while
	// still signed in is not the thing they asked for.
	DeleteOtherSessionsForUser(ctx context.Context, arg DeleteOtherSessionsForUserParams) (int64, error)
	// Logout. ADR-0005 chose opaque sessions precisely so this is all it takes:
	// one DELETE, effective on the next request, with no revocation list.
	DeleteSessionByTokenHash(ctx context.Context, tokenHash []byte) (int64, error)
	// Revoking one session. user_id is in the WHERE clause rather than checked in
	// Go after the row comes back: a session that is not the caller's must not be
	// deletable, and the only way to be sure of that is for the statement itself to
	// be unable to reach it. docs/authorization.md keeps sessions to their owner
	// even for `owner`.
	DeleteSessionForUser(ctx context.Context, arg DeleteSessionForUserParams) (int64, error)
	// Re-inviting somebody. The previous link stops working the moment a new one is
	// sent, rather than two links for one address both staying live -- an address
	// that was invited twice by mistake should not end up with a spare account
	// creator sitting in an old e-mail.
	//
	// lower(email) matches invitations_email_idx, which is partial on
	// accepted_at IS NULL and exists for exactly this lookup. Accepted rows are left
	// alone: they are the record that an account was created from this invitation,
	// and rewriting their deadline would rewrite that history.
	ExpireOpenInvitationsForEmail(ctx context.Context, email string) (int64, error)
	// Redemption. Expiry and acceptance are deliberately not filtered here, for the
	// same reason GetSessionByTokenHash does not filter expiry: the caller has to
	// tell an expired link from one that never existed for the log, and a WHERE
	// clause that hides the row makes the two indistinguishable. What the caller
	// must not do is let that difference reach the client — see Invitation.IsUsable.
	GetInvitationByTokenHash(ctx context.Context, tokenHash []byte) (GetInvitationByTokenHashRow, error)
	// Every authenticated request runs this, which is why it also returns the
	// user: the alternative is two round trips per request for data that is
	// always needed together.
	//
	// The join is against users_live, so a soft-deleted account stops
	// authenticating the moment it is masked — without a sweep having to reach its
	// sessions first. A join against users would keep them working until then.
	//
	// Expiry is deliberately not filtered here. The caller has to distinguish an
	// expired session from one that never existed for the log, and a WHERE clause
	// that hides the row makes the two indistinguishable.
	GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (GetSessionByTokenHashRow, error)
	// Login. Compared with lower() because addresses are not case sensitive and
	// users_email_key indexes lower(email) for exactly this lookup.
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	// Every read goes through users_live, never through users. The view is where
	// soft delete is enforced (docs/data-model.md); a query that names the table
	// directly is one forgotten WHERE away from returning deleted accounts.
	//
	// The two exceptions are the writes below, which have to name the table
	// because a view is not what you insert into or soft-delete through.
	GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error)
	// The account settings screen: what is signed in right now. The token hash is
	// never selected. Nothing outside authentication may see it, and a list
	// endpoint is exactly the place where one stray column becomes a credential
	// sitting in a JSON body.
	//
	// Expired rows are filtered rather than listed as dead. The question the screen
	// answers is "is anything signed in that should not be", and a row that can no
	// longer authenticate is not an answer to it. Removing them is a job (Langkah
	// 24); this only decides what is shown.
	ListSessionsByUser(ctx context.Context, userID string) ([]ListSessionsByUserRow, error)
	ListUsers(ctx context.Context) ([]ListUsersRow, error)
	// Masking, not deleting: the account keeps its rows so that its cards and
	// comments survive with an author (docs/data-model.md, retention). The address
	// is replaced rather than blanked so the partial unique index frees the
	// original for reuse.
	SoftDeleteUser(ctx context.Context, id string) (int64, error)
	// Sliding renewal. The caller decides how often this is worth running; see
	// Session.NeedsRenewal, which exists so this is not one write per request.
	TouchSession(ctx context.Context, arg TouchSessionParams) (int64, error)
	// Rewriting a hash at a cost the application has since raised. A successful
	// login is the only moment this is possible, because it is the only moment the
	// password is in memory.
	//
	// The old hash is matched as well as the id, so two logins racing each other
	// cannot have one overwrite the other's rehash with a stale value.
	UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
