// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one

INSERT INTO sessions (user_id, token_hash, user_agent, expires_at)
VALUES (
    $1,
    $2::bytea,
    $3::text,
    $4::timestamptz
)
RETURNING id, user_id, created_at, last_seen_at, expires_at
`

type CreateSessionParams struct {
	UserID    string
	TokenHash []byte
	UserAgent string
	ExpiresAt pgtype.Timestamptz
}

type CreateSessionRow struct {
	ID         string
	UserID     string
	CreatedAt  pgtype.Timestamptz
	LastSeenAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
}

// Sessions. The token itself never reaches this file: what is stored and what
// is looked up is its SHA-256, computed in the domain layer (ADR-0005).
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (CreateSessionRow, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.TokenHash,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	var i CreateSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteSessionByTokenHash = `-- name: DeleteSessionByTokenHash :execrows
DELETE FROM sessions
WHERE token_hash = $1::bytea
`

// Logout. ADR-0005 chose opaque sessions precisely so this is all it takes:
// one DELETE, effective on the next request, with no revocation list.
func (q *Queries) DeleteSessionByTokenHash(ctx context.Context, tokenHash []byte) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSessionByTokenHash, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT s.id,
       s.user_id,
       s.created_at,
       s.last_seen_at,
       s.expires_at,
       u.email,
       u.name,
       u.is_owner
FROM sessions s
JOIN users_live u ON u.id = s.user_id
WHERE s.token_hash = $1::bytea
`

type GetSessionByTokenHashRow struct {
	ID         string
	UserID     string
	CreatedAt  pgtype.Timestamptz
	LastSeenAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	Email      string
	Name       string
	IsOwner    bool
}

// Every authenticated request runs this, which is why it also returns the
// user: the alternative is two round trips per request for data that is
// always needed together.
//
// The join is against users_live, so a soft-deleted account stops
// authenticating the moment it is masked — without a sweep having to reach its
// sessions first. A join against users would keep them working until then.
//
// Expiry is deliberately not filtered here. The caller has to distinguish an
// expired session from one that never existed for the log, and a WHERE clause
// that hides the row makes the two indistinguishable.
func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.Email,
		&i.Name,
		&i.IsOwner,
	)
	return i, err
}

const touchSession = `-- name: TouchSession :execrows
UPDATE sessions
SET last_seen_at = now(),
    expires_at = $1::timestamptz
WHERE id = $2
`

type TouchSessionParams struct {
	ExpiresAt pgtype.Timestamptz
	ID        string
}

// Sliding renewal. The caller decides how often this is worth running; see
// Session.NeedsRenewal, which exists so this is not one write per request.
func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, touchSession, arg.ExpiresAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
