// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one

INSERT INTO sessions (user_id, token_hash, user_agent, expires_at)
VALUES (
    $1,
    $2::bytea,
    $3::text,
    $4::timestamptz
)
RETURNING id, user_id, created_at, last_seen_at, expires_at
`

type CreateSessionParams struct {
	UserID    string
	TokenHash []byte
	UserAgent string
	ExpiresAt pgtype.Timestamptz
}

type CreateSessionRow struct {
	ID         string
	UserID     string
	CreatedAt  pgtype.Timestamptz
	LastSeenAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
}

// Sessions. The token itself never reaches this file: what is stored and what
// is looked up is its SHA-256, computed in the domain layer (ADR-0005).
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (CreateSessionRow, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.TokenHash,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	var i CreateSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteOtherSessionsForUser = `-- name: DeleteOtherSessionsForUser :execrows
DELETE FROM sessions
WHERE user_id = $1
  AND id <> $2::uuid
`

type DeleteOtherSessionsForUserParams struct {
	UserID    string
	CurrentID string
}

// Signing out everywhere else. The session making the request is kept, because
// the caller asked to end the others and an answer they cannot receive while
// still signed in is not the thing they asked for.
func (q *Queries) DeleteOtherSessionsForUser(ctx context.Context, arg DeleteOtherSessionsForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOtherSessionsForUser, arg.UserID, arg.CurrentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSessionByTokenHash = `-- name: DeleteSessionByTokenHash :execrows
DELETE FROM sessions
WHERE token_hash = $1::bytea
`

// Logout. ADR-0005 chose opaque sessions precisely so this is all it takes:
// one DELETE, effective on the next request, with no revocation list.
func (q *Queries) DeleteSessionByTokenHash(ctx context.Context, tokenHash []byte) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSessionByTokenHash, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSessionForUser = `-- name: DeleteSessionForUser :execrows
DELETE FROM sessions
WHERE id = $1::uuid
  AND user_id = $2
`

type DeleteSessionForUserParams struct {
	ID     string
	UserID string
}

// Revoking one session. user_id is in the WHERE clause rather than checked in
// Go after the row comes back: a session that is not the caller's must not be
// deletable, and the only way to be sure of that is for the statement itself to
// be unable to reach it. docs/authorization.md keeps sessions to their owner
// even for `owner`.
func (q *Queries) DeleteSessionForUser(ctx context.Context, arg DeleteSessionForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSessionForUser, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT s.id,
       s.user_id,
       s.created_at,
       s.last_seen_at,
       s.expires_at,
       u.email,
       u.name,
       u.timezone,
       u.role
FROM sessions s
JOIN users_live u ON u.id = s.user_id
WHERE s.token_hash = $1::bytea
`

type GetSessionByTokenHashRow struct {
	ID         string
	UserID     string
	CreatedAt  pgtype.Timestamptz
	LastSeenAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	Email      string
	Name       string
	Timezone   string
	Role       string
}

// Every authenticated request runs this, which is why it also returns the
// user: the alternative is two round trips per request for data that is
// always needed together.
//
// The join is against users_live, so a soft-deleted account stops
// authenticating the moment it is masked — without a sweep having to reach its
// sessions first. A join against users would keep them working until then.
//
// Expiry is deliberately not filtered here. The caller has to distinguish an
// expired session from one that never existed for the log, and a WHERE clause
// that hides the row makes the two indistinguishable.
func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.Email,
		&i.Name,
		&i.Timezone,
		&i.Role,
	)
	return i, err
}

const listSessionsByUser = `-- name: ListSessionsByUser :many
SELECT id, user_agent, created_at, last_seen_at, expires_at
FROM sessions
WHERE user_id = $1
  AND expires_at > now()
ORDER BY last_seen_at DESC, id
`

type ListSessionsByUserRow struct {
	ID         string
	UserAgent  string
	CreatedAt  pgtype.Timestamptz
	LastSeenAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
}

// The account settings screen: what is signed in right now. The token hash is
// never selected. Nothing outside authentication may see it, and a list
// endpoint is exactly the place where one stray column becomes a credential
// sitting in a JSON body.
//
// Expired rows are filtered rather than listed as dead. The question the screen
// answers is "is anything signed in that should not be", and a row that can no
// longer authenticate is not an answer to it. Removing them is a job (Langkah
// 24); this only decides what is shown.
func (q *Queries) ListSessionsByUser(ctx context.Context, userID string) ([]ListSessionsByUserRow, error) {
	rows, err := q.db.Query(ctx, listSessionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionsByUserRow{}
	for rows.Next() {
		var i ListSessionsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserAgent,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchSession = `-- name: TouchSession :execrows
UPDATE sessions
SET last_seen_at = now(),
    expires_at = $1::timestamptz
WHERE id = $2
`

type TouchSessionParams struct {
	ExpiresAt pgtype.Timestamptz
	ID        string
}

// Sliding renewal. The caller decides how often this is worth running; see
// Session.NeedsRenewal, which exists so this is not one write per request.
func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, touchSession, arg.ExpiresAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
