// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, name, password_hash, is_owner)
VALUES (
    $1::text,
    $2::text,
    $3::text,
    $4::boolean
)
RETURNING id, email, name, is_owner, created_at
`

type CreateUserParams struct {
	Email        string
	Name         string
	PasswordHash string
	IsOwner      bool
}

type CreateUserRow struct {
	ID        string
	Email     string
	Name      string
	IsOwner   bool
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Name,
		arg.PasswordHash,
		arg.IsOwner,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.IsOwner,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, password_hash, is_owner, created_at, updated_at
FROM users_live
WHERE lower(email) = lower($1::text)
`

type GetUserByEmailRow struct {
	ID           string
	Email        string
	Name         string
	PasswordHash string
	IsOwner      bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

// Login. Compared with lower() because addresses are not case sensitive and
// users_email_key indexes lower(email) for exactly this lookup.
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.IsOwner,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one

SELECT id, email, name, password_hash, is_owner, created_at, updated_at
FROM users_live
WHERE id = $1
`

type GetUserByIDRow struct {
	ID           string
	Email        string
	Name         string
	PasswordHash string
	IsOwner      bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

// Every read goes through users_live, never through users. The view is where
// soft delete is enforced (docs/data-model.md); a query that names the table
// directly is one forgotten WHERE away from returning deleted accounts.
//
// The two exceptions are the writes below, which have to name the table
// because a view is not what you insert into or soft-delete through.
func (q *Queries) GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.IsOwner,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, name, is_owner, created_at
FROM users_live
ORDER BY lower(name)
`

type ListUsersRow struct {
	ID        string
	Email     string
	Name      string
	IsOwner   bool
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.IsOwner,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteUser = `-- name: SoftDeleteUser :execrows
UPDATE users
SET deleted_at = now(),
    email = 'deleted+' || id::text || '@invalid',
    name = 'Pengguna dihapus',
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
`

// Masking, not deleting: the account keeps its rows so that its cards and
// comments survive with an author (docs/data-model.md, retention). The address
// is replaced rather than blanked so the partial unique index frees the
// original for reuse.
func (q *Queries) SoftDeleteUser(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
